{% set name = "romkan" %}
{% set version = "0.2.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "a530245a38969704700e0ca8f9cb7158c4ede91c5fd1e24677dbe814cf91f33b" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - romkan

about:
  home: http://www.soimort.org/python-romkan/
  license: BSD License
  license_family: BSD
  license_file: ''
  summary: A Romaji/Kana conversion library
  description: "python-romkan\n=============\n\n`python-romkan <https://github.com/soimort/python-romkan>`_ is a Romaji/Kana conversion library for Python, which is used to convert a Japanese Romaji (\u30ED\
    \u30FC\u30DE\u5B57) string to a Japanese Kana (\u4EEE\u540D) string or vice versa.\n\nIt is the Pythonic port of `Ruby/Romkan <http://0xcc.net/ruby-romkan/index.html.en>`_, originally authored by Satoru\
    \ Takabayashi and `ported <http://lilyx.net/python-romkan/>`_ by Masato Hagiwara.\n\n`python-romkan <https://github.com/soimort/python-romkan>`_ works on Python 2 and Python 3 (fully tested on **Python\
    \ 2.6**, **2.7**, **3.2**, **3.3** and **PyPy**). It handles both Katakana (\u7247\u4EEE\u540D) and Hiragana (\u5E73\u4EEE\u540D) with the Hepburn (\u30D8\u30DC\u30F3\u5F0F) romanization system, as\
    \ well as the modern Kunrei-shiki (\u8A13\u4EE4\u5F0F) romanization system.\n\nProject homepage: http://www.soimort.org/python-romkan\n\nFork me on GitHub: https://github.com/soimort/python-romkan\n\
    \n.. image:: https://api.travis-ci.org/soimort/python-romkan.png\n\n\n\nInstallation\n------------\n\n#) Install via `Pip <http://www.pip-installer.org/>`_::\n\n    $ pip install romkan\n    \n#) Install\
    \ via `EasyInstall <http://pypi.python.org/pypi/setuptools>`_::\n\n    $ easy_install romkan\n    \n#) Install from Git::\n\n    $ git clone git://github.com/soimort/python-romkan.git\n    $ python\
    \ setup.py install\n\n\n\nUsage\n-----\n\nPython 3.x::\n\n    $ python\n    >>> import romkan\n    >>> print(romkan.to_roma(\"\u306B\u3093\u3058\u3083\"))\n    ninja\n    >>> print(romkan.to_hepburn(\"\
    \u306B\u3093\u3058\u3083\"))\n    ninja\n    >>> print(romkan.to_kunrei(\"\u306B\u3093\u3058\u3083\"))\n    ninzya\n    >>> print(romkan.to_hiragana(\"ninja\"))\n    \u306B\u3093\u3058\u3083\n    >>>\
    \ print(romkan.to_katakana(\"ninja\"))\n    \u30CB\u30F3\u30B8\u30E3\n\nPython 2.x::\n\n    $ python2\n    >>> import romkan\n    >>> print romkan.to_roma(u\"\u306B\u3093\u3058\u3083\")\n    ninja\n\
    \    >>> print romkan.to_hepburn(u\"\u306B\u3093\u3058\u3083\")\n    ninja\n    >>> print romkan.to_kunrei(u\"\u306B\u3093\u3058\u3083\")\n    ninzya\n    >>> print romkan.to_hiragana(\"ninja\")\n \
    \   \u306B\u3093\u3058\u3083\n    >>> print romkan.to_katakana(\"ninja\")\n    \u30CB\u30F3\u30B8\u30E3\n\n\n\nAPI Reference\n-------------\n\n* **to_katakana(string)**\n\nConvert a Romaji (\u30ED\u30FC\
    \u30DE\u5B57) to a Katakana (\u7247\u4EEE\u540D).\n\n* **to_hiragana(string)**\n\nConvert a Romaji (\u30ED\u30FC\u30DE\u5B57) to a Hiragana (\u5E73\u4EEE\u540D).\n\n* **to_kana(string)**\n\nConvert\
    \ a Romaji (\u30ED\u30FC\u30DE\u5B57) to a Katakana (\u7247\u4EEE\u540D). (same as *to_katakana*)\n\n* **to_hepburn(string)**\n\nConvert a Kana (\u4EEE\u540D) or a Kunrei-shiki Romaji (\u8A13\u4EE4\u5F0F\
    \u30ED\u30FC\u30DE\u5B57) to a Hepburn Romaji (\u30D8\u30DC\u30F3\u5F0F\u30ED\u30FC\u30DE\u5B57).\n\n* **to_kunrei(string)**\n\nConvert a Kana (\u4EEE\u540D) or a Hepburn Romaji (\u30D8\u30DC\u30F3\u5F0F\
    \u30ED\u30FC\u30DE\u5B57) to a Kunrei-shiki Romaji (\u8A13\u4EE4\u5F0F\u30ED\u30FC\u30DE\u5B57).\n\n* **to_roma(string)**\n\nConvert a Kana (\u4EEE\u540D) to a Hepburn Romaji (\u30D8\u30DC\u30F3\u5F0F\
    \u30ED\u30FC\u30DE\u5B57).\n\n\n\nLicense\n-------\n\n`python-romkan <https://github.com/soimort/python-romkan>`_ is licensed under the `BSD license <https://raw.github.com/soimort/python-romkan/master/LICENSE>`_.\n\
    \n\nChangelog\n=========\n\n0.2.1\n-----\n\n*Date: 2013-02-26*\n\n* Improved Python compatibility (2.6, <=3.1).\n\n0.2.0\n-----\n\n*Date: 2013-02-21*\n\n* Fixed the explicit unicode literal issue on\
    \ Python 3.2.\n* Tested on Travis CI for Python 2.7, 3.2, 3.3 and PyPy.\n\n0.1.0\n-----\n\n*Date: 2013-02-12*\n\n0.0.2\n-----\n\n*Date: 2013-01-29*\n\n* Fixed #1.\n\n0.0.1\n-----\n\n*Date: 2012-12-06*\n\
    \n* Initial release."
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
